/* Repeating Subsequence */

/* Problem Description
Given a string A, find if there is any subsequence that repeats itself.

A subsequence of a string is defined as a sequence of characters generated by deleting some characters in the string without changing the order of the remaining characters.

NOTE:
1. Subsequence length should be greater than or equal to 2.
2. The repeating subsequence should be disjoint that is no index in the original subsequence should be present in the repeated subsequence.


Problem Constraints
1 <= length(A) <= 100


Input Format
The first and the only argument of input contains a string A.


Output Format
Return an integer, 1 if there is any subsequence which repeat itself else return 0.


Example Input
Input 1:
 A = "abab"
Input 2:
 A = "abba"


Example Output
Output 1:
 1
Output 2:
 0


Example Explanation
Explanation 1:
 "ab" is repeated.
Explanation 2:
 There is no repeating subsequence. */
public class hw_q2_Repeating_Subsequence {

    public int anyTwo(String A) {
        return lcs(A, A) > 1 ? 1 : 0;
    }

    public int lcs(String A, String B) {

        int n = A.length();
        int[][] dp = new int[n + 1][n + 1];

        for (int i = n; i >= 0; i--) {
            for (int j = n; j >= 0; j--) {
                if (i == n || j == n)
                    dp[i][j] = 0;
                else if (A.charAt(i) == B.charAt(j) && i != j) {
                    dp[i][j] = Math.max(dp[i + 1][j + 1] + 1, Math.max(dp[i + 1][j], dp[i][j + 1]));
                } else {
                    dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]);
                }
            }
        }
        return dp[0][0];
    }

    public static void main(String[] args) {

        hw_q2_Repeating_Subsequence t1 = new hw_q2_Repeating_Subsequence();
        String A;

        // test case 1
        A = "aabb";
        System.out.println(t1.anyTwo(A));

        // test case 2
        A = "abab";
        System.out.println(t1.anyTwo(A));

        // test case 3
        A = "wrBqHDrOKyiDSdrMwrsylBFacyEDGxPLRlNPPFkoKCqNNUwSMbUcjiSmKtXXvrbjtsFZfMFdRSFBNVhfSqwQ";
        System.out.println(t1.anyTwo(A));

        // test case 4
        A = "abba";
        System.out.println(t1.anyTwo(A));
    }

}
